### PR TITLE
Add play-services-cast dummy implementation

### PR DESCRIPTION
**Pull request by moparisthebest**
I wrote this mainly so f-droid could stop removing apps that add cast support, and instead just compile without cast support but also without source modification.

You'll have to forgive me, I've never made changes in a repo with submodules where I also had to fork/change the submodules, and I don't know the "correct" way to do so, here are where I pushed the forked submodules:

https://github.com/moparisthebest/android_external_GmsApi
https://github.com/moparisthebest/android_external_SafeParcel

The submodules only needed token changes to work with gradle 2.4, so maybe we can even just ignore them.

### CODE REVIEW

**Comment by xmikos** [comment]
I see many lines like this in diff:

> // Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
> // Jad home page: http://www.geocities.com/kpdus/jad.html
> // Decompiler options: packimports(3)

Are you actually promoting patch created by decompilation of proprietary apk? This would be legal nightmare for microG project...

**Comment by mimi89999** [comment]
I agree with @xmikos

**Comment by xmikos** [comment]
Well, I didn't look at date, this pull request is probably outdated (it seems that Cast support is already included). It should be closed :-)

**Comment by mimi89999** [comment]
@moparisthebest 
1. Do you understand, that if this PR is merged, it will be the end of this project?
2. From the ethical point of view: If you decompile some proprietary code and publish it under a free license, will it really be free software?

**Comment by moparisthebest** [comment]
I don't see a problem with it?  I used the decompiler to get public class/method signatures and that is it (only the API), no actual decompiled code was used.  So what exactly is the problem?

**Comment by mimi89999** [comment]
> no actual decompiled code was used.

It was unclear.

**Comment by moparisthebest** [comment]
That's fair, I should have removed the comments from the top I suppose.

Anyway it looks like play-services-cast has been added independent of this, so I'll just go ahead and close it. :)

**Pull request closed without merging**
